name: Reclaim The Stack - Rubocop
description: Runs rubocop and posts offences as inline PR comments.
inputs:
  github_token:
    description: GITHUB_TOKEN
    default: ${{ github.token }}
  gem_versions:
    description: Gem versions to install
    default: rubocop:1.54.1 rubocop-rails:2.20.2 rubocop-rspec:2.22.0
  outside_diff:
    description: Log offences found outside of PR diff
    default: "true"
  rubocop_arguments:
    description: Arguments passed to rubocop cli
    default: ""
runs:
  using: composite
  steps:
    - run: ruby $GITHUB_ACTION_PATH/rubocop.rb ${{ inputs.rubocop_arguments }}
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
        OUTSIDE_DIFF: ${{ inputs.outside_diff }}
        RUBOCOP_GEM_VERSIONS: ${{ inputs.gem_versions }}
